spring:
  security:
    user:
      name: ${USER:user}
      password: ${PW:asdf}
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    name: super_pal
    username: sa
    password: asdf
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect